version: "3.0"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=${DBNAME}
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASS}
  web:
    build: .
    user: deaconn
    command: bash -c "./start.sh"
    environment:
      - POSTGRES_NAME=${DBNAME}
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASS}
      - 'DJANGO_KEY=${SECRET_KEY}'
      - PYTHONPATH=/deaconn/.local/lib/python3.10:/deaconn/.local/lib/python3.10/site-packages
      - PATH=${PATH}:/deaconn/.local/bin
    depends_on:
      - db