version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=${DBNAME}
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASS}
  web:
    build: .
    user: deaconn
    command: bash -c "./start.sh"
    volumes:
      - ./back-bone:/deaconn/back-bone
      - ./media:/deaconn/media
      - ./static:/deaconn/static
      - ./data-web:/deaconn/data
    environment:
      - POSTGRES_NAME=${DBNAME}
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASS}
      - 'DJANGO_KEY=${SECRET_KEY}'
      - PYTHONPATH=/deaconn/.local/lib/python3.10:/deaconn/.local/lib/python3.10/site-packages
      - PATH=${PATH}:/deaconn/.local/bin
    depends_on:
      - db